using System;
using System.Collections.Generic;

namespace DalUnlocker
{
    public partial class Tb00015
    {
        public string Tb00015Nomenota { get; set; }
        public int? Tb00015Qtdecolform { get; set; }
        public int? Tb00015Qtdelinform { get; set; }
        public int? Tb00015Tamfonte { get; set; }
        public int? Tb00015Avanco { get; set; }
        public int? Tb00015Espacamentolin { get; set; }
        public int? Tb00015Qtdeitenspornota { get; set; }
        public int? Tb00015Tiposaidalin { get; set; }
        public int? Tb00015Tiposaidacol { get; set; }
        public int? Tb00015Tipoentradalin { get; set; }
        public int? Tb00015Tipoentradacol { get; set; }
        public int? Tb00015Numerolin { get; set; }
        public int? Tb00015Numerocol { get; set; }
        public int? Tb00015Naturezalin { get; set; }
        public int? Tb00015Naturezacol { get; set; }
        public int? Tb00015Cfoplin { get; set; }
        public int? Tb00015Cfopcol { get; set; }
        public int? Tb00015Inscestlin { get; set; }
        public int? Tb00015Inscestcol { get; set; }
        public int? Tb00015Dtemissaolin { get; set; }
        public int? Tb00015Dtemissaocol { get; set; }
        public int? Tb00015Dtsaidalin { get; set; }
        public int? Tb00015Dtsaidacol { get; set; }
        public int? Tb00015Horasaidalin { get; set; }
        public int? Tb00015Horasaidacol { get; set; }
        public int? Tb00015Razaosociallin { get; set; }
        public int? Tb00015Razaosocialcol { get; set; }
        public int? Tb00015Cnpjlin { get; set; }
        public int? Tb00015Cnpjcol { get; set; }
        public int? Tb00015Enderecolin { get; set; }
        public int? Tb00015Enderecocol { get; set; }
        public int? Tb00015Bairrolin { get; set; }
        public int? Tb00015Bairrocol { get; set; }
        public int? Tb00015Ceplin { get; set; }
        public int? Tb00015Cepcol { get; set; }
        public int? Tb00015Municipiolin { get; set; }
        public int? Tb00015Municipiocol { get; set; }
        public int? Tb00015Tellin { get; set; }
        public int? Tb00015Telcol { get; set; }
        public int? Tb00015Uflin { get; set; }
        public int? Tb00015Ufcol { get; set; }
        public int? Tb00015Inscestclientelin { get; set; }
        public int? Tb00015Inscestclientecol { get; set; }
        public int? Tb00015Basecalicmslin { get; set; }
        public int? Tb00015Basecalicmscol { get; set; }
        public int? Tb00015Valoricmslin { get; set; }
        public int? Tb00015Valoricmscol { get; set; }
        public int? Tb00015Basecalicmssubstlin { get; set; }
        public int? Tb00015Basecalicmssubstcol { get; set; }
        public int? Tb00015Valoricmssubstlin { get; set; }
        public int? Tb00015Valoricmssubstcol { get; set; }
        public int? Tb00015Valorfretelin { get; set; }
        public int? Tb00015Valorfretecol { get; set; }
        public int? Tb00015Valorsegurolin { get; set; }
        public int? Tb00015Valorsegurocol { get; set; }
        public int? Tb00015Outrasdesplin { get; set; }
        public int? Tb00015Outrasdespcol { get; set; }
        public int? Tb00015Valortotalipilin { get; set; }
        public int? Tb00015Valortotalipicol { get; set; }
        public int? Tb00015Valortotalprodlin { get; set; }
        public int? Tb00015Valortotalprodcol { get; set; }
        public int? Tb00015Valortotalnotalin { get; set; }
        public int? Tb00015Valortotalnotacol { get; set; }
        public int? Tb00015Razaosocialtransplin { get; set; }
        public int? Tb00015Razaosocialtranspcol { get; set; }
        public int? Tb00015Fretetransplin { get; set; }
        public int? Tb00015Fretetranspcol { get; set; }
        public int? Tb00015Placatransplin { get; set; }
        public int? Tb00015Placatranspcol { get; set; }
        public int? Tb00015Ufveitransplin { get; set; }
        public int? Tb00015Ufveitranspcol { get; set; }
        public int? Tb00015Cnpjtransplin { get; set; }
        public int? Tb00015Cnpjtranspcol { get; set; }
        public int? Tb00015Enderecotransplin { get; set; }
        public int? Tb00015Enderecotranspcol { get; set; }
        public int? Tb00015Municipiotransplin { get; set; }
        public int? Tb00015Municipiotranspcol { get; set; }
        public int? Tb00015Uftransplin { get; set; }
        public int? Tb00015Uftranspcol { get; set; }
        public int? Tb00015Inscesttransplin { get; set; }
        public int? Tb00015Inscesttranspcol { get; set; }
        public int? Tb00015Quanttransplin { get; set; }
        public int? Tb00015Quanttranspcol { get; set; }
        public int? Tb00015Especietransplin { get; set; }
        public int? Tb00015Especietranspcol { get; set; }
        public int? Tb00015Marcatransplin { get; set; }
        public int? Tb00015Marcatranspcol { get; set; }
        public int? Tb00015Numerotransplin { get; set; }
        public int? Tb00015Numerotranspcol { get; set; }
        public int? Tb00015Pesobrutotransplin { get; set; }
        public int? Tb00015Pesobrutotranspcol { get; set; }
        public int? Tb00015Pesoliquidotransplin { get; set; }
        public int? Tb00015Pesoliquidotranspcol { get; set; }
        public int? Tb00015Codprodlin { get; set; }
        public int? Tb00015Codprodcol { get; set; }
        public int? Tb00015Descprodlin { get; set; }
        public int? Tb00015Descprodcol { get; set; }
        public int? Tb00015Clfiscallin { get; set; }
        public int? Tb00015Clfiscalcol { get; set; }
        public int? Tb00015Cstlin { get; set; }
        public int? Tb00015Cstcol { get; set; }
        public int? Tb00015Unidadelin { get; set; }
        public int? Tb00015Unidadecol { get; set; }
        public int? Tb00015Quantlin { get; set; }
        public int? Tb00015Quantcol { get; set; }
        public int? Tb00015Valorunitlin { get; set; }
        public int? Tb00015Valorunitcol { get; set; }
        public int? Tb00015Valortotallin { get; set; }
        public int? Tb00015Valortotalcol { get; set; }
        public int? Tb00015Aliqicmslin { get; set; }
        public int? Tb00015Aliqicmscol { get; set; }
        public int? Tb00015Aliqipilin { get; set; }
        public int? Tb00015Aliqipicol { get; set; }
        public int? Tb00015Valoripilin { get; set; }
        public int? Tb00015Valoripicol { get; set; }
        public int? Tb00015Dadosaddlin { get; set; }
        public int? Tb00015Dadosaddcol { get; set; }
        public int? Tb00015Numcontrolformlin { get; set; }
        public int? Tb00015Numcontrolformcol { get; set; }
        public int Tb00015Codigo { get; set; }
    }
}