using System;
using System.Collections.Generic;

namespace DalUnlocker
{
    public partial class Tb01050
    {
        public string Tb01050Produto { get; set; }
        public string Tb01050Estado { get; set; }
        public decimal? Tb01050AcIcms { get; set; }
        public decimal? Tb01050AlIcms { get; set; }
        public decimal? Tb01050AmIcms { get; set; }
        public decimal? Tb01050ApIcms { get; set; }
        public decimal? Tb01050BaIcms { get; set; }
        public decimal? Tb01050CeIcms { get; set; }
        public decimal? Tb01050DfIcms { get; set; }
        public decimal? Tb01050EsIcms { get; set; }
        public decimal? Tb01050GoIcms { get; set; }
        public decimal? Tb01050MaIcms { get; set; }
        public decimal? Tb01050MgIcms { get; set; }
        public decimal? Tb01050MsIcms { get; set; }
        public decimal? Tb01050MtIcms { get; set; }
        public decimal? Tb01050PaIcms { get; set; }
        public decimal? Tb01050PbIcms { get; set; }
        public decimal? Tb01050PeIcms { get; set; }
        public decimal? Tb01050PiIcms { get; set; }
        public decimal? Tb01050PrIcms { get; set; }
        public decimal? Tb01050RjIcms { get; set; }
        public decimal? Tb01050RnIcms { get; set; }
        public decimal? Tb01050RoIcms { get; set; }
        public decimal? Tb01050RrIcms { get; set; }
        public decimal? Tb01050RsIcms { get; set; }
        public decimal? Tb01050ScIcms { get; set; }
        public decimal? Tb01050SeIcms { get; set; }
        public decimal? Tb01050SpIcms { get; set; }
        public decimal? Tb01050ToIcms { get; set; }
        public decimal? Tb01050AcMva { get; set; }
        public decimal? Tb01050AlMva { get; set; }
        public decimal? Tb01050AmMva { get; set; }
        public decimal? Tb01050ApMva { get; set; }
        public decimal? Tb01050BaMva { get; set; }
        public decimal? Tb01050CeMva { get; set; }
        public decimal? Tb01050DfMva { get; set; }
        public decimal? Tb01050EsMva { get; set; }
        public decimal? Tb01050GoMva { get; set; }
        public decimal? Tb01050MaMva { get; set; }
        public decimal? Tb01050MgMva { get; set; }
        public decimal? Tb01050MsMva { get; set; }
        public decimal? Tb01050MtMva { get; set; }
        public decimal? Tb01050PaMva { get; set; }
        public decimal? Tb01050PbMva { get; set; }
        public decimal? Tb01050PeMva { get; set; }
        public decimal? Tb01050PiMva { get; set; }
        public decimal? Tb01050PrMva { get; set; }
        public decimal? Tb01050RjMva { get; set; }
        public decimal? Tb01050RnMva { get; set; }
        public decimal? Tb01050RoMva { get; set; }
        public decimal? Tb01050RrMva { get; set; }
        public decimal? Tb01050RsMva { get; set; }
        public decimal? Tb01050ScMva { get; set; }
        public decimal? Tb01050SeMva { get; set; }
        public decimal? Tb01050SpMva { get; set; }
        public decimal? Tb01050ToMva { get; set; }
        public decimal? Tb01050Icms { get; set; }
        public decimal? Tb01050Icmsst { get; set; }
        public decimal? Tb01050Mva { get; set; }
        public string Tb01050AcDif { get; set; }
        public string Tb01050AlDif { get; set; }
        public string Tb01050AmDif { get; set; }
        public string Tb01050ApDif { get; set; }
        public string Tb01050BaDif { get; set; }
        public string Tb01050CeDif { get; set; }
        public string Tb01050DfDif { get; set; }
        public string Tb01050EsDif { get; set; }
        public string Tb01050GoDif { get; set; }
        public string Tb01050MaDif { get; set; }
        public string Tb01050MgDif { get; set; }
        public string Tb01050MsDif { get; set; }
        public string Tb01050MtDif { get; set; }
        public string Tb01050PaDif { get; set; }
        public string Tb01050PbDif { get; set; }
        public string Tb01050PeDif { get; set; }
        public string Tb01050PiDif { get; set; }
        public string Tb01050PrDif { get; set; }
        public string Tb01050RjDif { get; set; }
        public string Tb01050RnDif { get; set; }
        public string Tb01050RoDif { get; set; }
        public string Tb01050RrDif { get; set; }
        public string Tb01050RsDif { get; set; }
        public string Tb01050ScDif { get; set; }
        public string Tb01050SeDif { get; set; }
        public string Tb01050SpDif { get; set; }
        public string Tb01050ToDif { get; set; }
        public decimal? Tb01050AcFcp { get; set; }
        public decimal? Tb01050AlFcp { get; set; }
        public decimal? Tb01050AmFcp { get; set; }
        public decimal? Tb01050ApFcp { get; set; }
        public decimal? Tb01050BaFcp { get; set; }
        public decimal? Tb01050CeFcp { get; set; }
        public decimal? Tb01050DfFcp { get; set; }
        public decimal? Tb01050EsFcp { get; set; }
        public decimal? Tb01050GoFcp { get; set; }
        public decimal? Tb01050MaFcp { get; set; }
        public decimal? Tb01050MgFcp { get; set; }
        public decimal? Tb01050MsFcp { get; set; }
        public decimal? Tb01050MtFcp { get; set; }
        public decimal? Tb01050PaFcp { get; set; }
        public decimal? Tb01050PbFcp { get; set; }
        public decimal? Tb01050PeFcp { get; set; }
        public decimal? Tb01050PiFcp { get; set; }
        public decimal? Tb01050PrFcp { get; set; }
        public decimal? Tb01050RjFcp { get; set; }
        public decimal? Tb01050RnFcp { get; set; }
        public decimal? Tb01050RoFcp { get; set; }
        public decimal? Tb01050RrFcp { get; set; }
        public decimal? Tb01050RsFcp { get; set; }
        public decimal? Tb01050ScFcp { get; set; }
        public decimal? Tb01050SeFcp { get; set; }
        public decimal? Tb01050SpFcp { get; set; }
        public decimal? Tb01050ToFcp { get; set; }
        public string Tb01050AcMvaajustado { get; set; }
        public string Tb01050AlMvaajustado { get; set; }
        public string Tb01050AmMvaajustado { get; set; }
        public string Tb01050ApMvaajustado { get; set; }
        public string Tb01050BaMvaajustado { get; set; }
        public string Tb01050CeMvaajustado { get; set; }
        public string Tb01050DfMvaajustado { get; set; }
        public string Tb01050EsMvaajustado { get; set; }
        public string Tb01050GoMvaajustado { get; set; }
        public string Tb01050MaMvaajustado { get; set; }
        public string Tb01050MgMvaajustado { get; set; }
        public string Tb01050MsMvaajustado { get; set; }
        public string Tb01050MtMvaajustado { get; set; }
        public string Tb01050PaMvaajustado { get; set; }
        public string Tb01050PbMvaajustado { get; set; }
        public string Tb01050PeMvaajustado { get; set; }
        public string Tb01050PiMvaajustado { get; set; }
        public string Tb01050PrMvaajustado { get; set; }
        public string Tb01050RjMvaajustado { get; set; }
        public string Tb01050RnMvaajustado { get; set; }
        public string Tb01050RoMvaajustado { get; set; }
        public string Tb01050RrMvaajustado { get; set; }
        public string Tb01050RsMvaajustado { get; set; }
        public string Tb01050ScMvaajustado { get; set; }
        public string Tb01050SeMvaajustado { get; set; }
        public string Tb01050SpMvaajustado { get; set; }
        public string Tb01050ToMvaajustado { get; set; }
        public decimal? Tb01050AcIcmsint { get; set; }
        public decimal? Tb01050AlIcmsint { get; set; }
        public decimal? Tb01050AmIcmsint { get; set; }
        public decimal? Tb01050ApIcmsint { get; set; }
        public decimal? Tb01050BaIcmsint { get; set; }
        public decimal? Tb01050CeIcmsint { get; set; }
        public decimal? Tb01050DfIcmsint { get; set; }
        public decimal? Tb01050EsIcmsint { get; set; }
        public decimal? Tb01050GoIcmsint { get; set; }
        public decimal? Tb01050MaIcmsint { get; set; }
        public decimal? Tb01050MgIcmsint { get; set; }
        public decimal? Tb01050MsIcmsint { get; set; }
        public decimal? Tb01050MtIcmsint { get; set; }
        public decimal? Tb01050PaIcmsint { get; set; }
        public decimal? Tb01050PbIcmsint { get; set; }
        public decimal? Tb01050PeIcmsint { get; set; }
        public decimal? Tb01050PiIcmsint { get; set; }
        public decimal? Tb01050PrIcmsint { get; set; }
        public decimal? Tb01050RjIcmsint { get; set; }
        public decimal? Tb01050RnIcmsint { get; set; }
        public decimal? Tb01050RoIcmsint { get; set; }
        public decimal? Tb01050RrIcmsint { get; set; }
        public decimal? Tb01050RsIcmsint { get; set; }
        public decimal? Tb01050ScIcmsint { get; set; }
        public decimal? Tb01050SeIcmsint { get; set; }
        public decimal? Tb01050SpIcmsint { get; set; }
        public decimal? Tb01050ToIcmsint { get; set; }
        public decimal? Tb01050AcMvaint { get; set; }
        public decimal? Tb01050AlMvaint { get; set; }
        public decimal? Tb01050AmMvaint { get; set; }
        public decimal? Tb01050ApMvaint { get; set; }
        public decimal? Tb01050BaMvaint { get; set; }
        public decimal? Tb01050CeMvaint { get; set; }
        public decimal? Tb01050DfMvaint { get; set; }
        public decimal? Tb01050EsMvaint { get; set; }
        public decimal? Tb01050GoMvaint { get; set; }
        public decimal? Tb01050MaMvaint { get; set; }
        public decimal? Tb01050MgMvaint { get; set; }
        public decimal? Tb01050MsMvaint { get; set; }
        public decimal? Tb01050MtMvaint { get; set; }
        public decimal? Tb01050PaMvaint { get; set; }
        public decimal? Tb01050PbMvaint { get; set; }
        public decimal? Tb01050PeMvaint { get; set; }
        public decimal? Tb01050PiMvaint { get; set; }
        public decimal? Tb01050PrMvaint { get; set; }
        public decimal? Tb01050RjMvaint { get; set; }
        public decimal? Tb01050RnMvaint { get; set; }
        public decimal? Tb01050RoMvaint { get; set; }
        public decimal? Tb01050RrMvaint { get; set; }
        public decimal? Tb01050RsMvaint { get; set; }
        public decimal? Tb01050ScMvaint { get; set; }
        public decimal? Tb01050SeMvaint { get; set; }
        public decimal? Tb01050SpMvaint { get; set; }
        public decimal? Tb01050ToMvaint { get; set; }
    }
}