using System;
using System.Collections.Generic;

namespace DalUnlocker
{
    public partial class Tb02021
    {
        public DateTime? Tb02021Dtcad { get; set; }
        public string Tb02021Opcad { get; set; }
        public DateTime? Tb02021Dtalt { get; set; }
        public string Tb02021Opalt { get; set; }
        public decimal? Tb02021Baseicms { get; set; }
        public decimal? Tb02021Baseicmssub { get; set; }
        public string Tb02021Codemp { get; set; }
        public string Tb02021Codcli { get; set; }
        public string Tb02021Codigo { get; set; }
        public string Tb02021Condpag { get; set; }
        public string Tb02021Codtec { get; set; }
        public DateTime? Tb02021Data { get; set; }
        public DateTime? Tb02021Dtent { get; set; }
        public string Tb02021Defeito { get; set; }
        public decimal? Tb02021Despadd { get; set; }
        public string Tb02021Equip { get; set; }
        public string Tb02021Espercie { get; set; }
        public string Tb02021Horastrab { get; set; }
        public string Tb02021Horascom { get; set; }
        public string Tb02021Horasfim { get; set; }
        public string Tb02021Laudo { get; set; }
        public string Tb02021Marca { get; set; }
        public string Tb02021Ntfisc { get; set; }
        public string Tb02021Numero { get; set; }
        public string Tb02021Numorc { get; set; }
        public string Tb02021Obs { get; set; }
        public string Tb02021Obsadd { get; set; }
        public string Tb02021Obsint { get; set; }
        public int? Tb02021Operacao { get; set; }
        public decimal? Tb02021Percdesconto { get; set; }
        public string Tb02021Prest { get; set; }
        public decimal? Tb02021Qtde { get; set; }
        public int? Tb02021Qtvolumes { get; set; }
        public string Tb02021Respent { get; set; }
        public string Tb02021Situacao { get; set; }
        public string Tb02021Status { get; set; }
        public string Tb02021Tipodesc { get; set; }
        public string Tb02021Transp { get; set; }
        public string Tb02021Vend { get; set; }
        public decimal? Tb02021Vlrbruto { get; set; }
        public decimal? Tb02021Vlrdesconto { get; set; }
        public decimal? Tb02021Vlrfrete { get; set; }
        public decimal? Tb02021Vlricms { get; set; }
        public decimal? Tb02021Vlricmssub { get; set; }
        public decimal? Tb02021Vlripi { get; set; }
        public decimal? Tb02021Vlrprest { get; set; }
        public decimal? Tb02021Vlrnota { get; set; }
        public decimal? Tb02021Vlroutdesp { get; set; }
        public decimal? Tb02021Vlrserv { get; set; }
        public decimal? Tb02021Vlrpago { get; set; }
        public decimal? Tb02021Vlrtroco { get; set; }
        public string Tb02021Numserie { get; set; }
        public string Tb02021Natureza { get; set; }
        public string Tb02021Codcai { get; set; }
        public string Tb02021Placa { get; set; }
        public string Tb02021Ufplaca { get; set; }
        public decimal? Tb02021Pesobruto { get; set; }
        public decimal? Tb02021Pesoliquido { get; set; }
        public DateTime? Tb02021Datanota { get; set; }
        public string Tb02021Horanota { get; set; }
        public string Tb02021Poscli { get; set; }
        public string Tb02021Contabil { get; set; }
        public int? Tb02021Tipofrete { get; set; }
        public string Tb02021Ntserv { get; set; }
        public string Tb02021Serie { get; set; }
        public string Tb02021Subserie { get; set; }
        public string Tb02021Vendacons { get; set; }
        public decimal? Tb02021Vlrbackup { get; set; }
        public string Tb02021Nome { get; set; }
        public string Tb02021Fone { get; set; }
        public string Tb02021Codrev { get; set; }
        public string Tb02021Codcen { get; set; }
        public string Tb02021Codsub { get; set; }
        public string Tb02021Plancon { get; set; }
        public decimal? Tb02021Vlrdescacu { get; set; }
        public decimal? Tb02021Perccond { get; set; }
        public decimal? Tb02021Vlrover { get; set; }
        public decimal? Tb02021Vlrimpostos { get; set; }
        public string Tb02021Emailpag { get; set; }
        public string Tb02021Emailent { get; set; }
        public DateTime? Tb02021Dataexec { get; set; }
        public decimal? Tb02021Vlrfrete2 { get; set; }
        public decimal? Tb02021Vlroutdesp2 { get; set; }
        public int? Tb02021Contpb { get; set; }
        public int? Tb02021Contcolor { get; set; }
        public string Tb02021Bonif { get; set; }
        public string Tb02021Nestoque { get; set; }
        public string Tb02021Tipoestoque { get; set; }
        public string Tb02021Sped { get; set; }
        public decimal? Tb02021Basepis { get; set; }
        public decimal? Tb02021Basecofins { get; set; }
        public decimal? Tb02021Vlrpis { get; set; }
        public decimal? Tb02021Vlrcofins { get; set; }
        public decimal? Tb02021Vlriss { get; set; }
        public string Tb02021Nfse { get; set; }
        public decimal? Tb02021Vlrcsll { get; set; }
        public decimal? Tb02021Vlrir { get; set; }
        public decimal? Tb02021Vlrretpis { get; set; }
        public decimal? Tb02021Vlrretcofins { get; set; }
        public decimal? Tb02021Vlrretcsll { get; set; }
        public decimal? Tb02021Vlrretir { get; set; }
        public decimal? Tb02021Vlrretiss { get; set; }
        public string Tb02021Modulo { get; set; }
        public string Tb02021Coddef { get; set; }
        public string Tb02021Cupom { get; set; }
        public int? Tb02021Modeloecf { get; set; }
        public string Tb02021Codecf { get; set; }
        public string Tb02021Natuoperserv { get; set; }
        public string Tb02021Codtributacao { get; set; }
        public string Tb02021Subitem { get; set; }
        public string Tb02021Clatende { get; set; }
        public string Tb02021Muntribserv { get; set; }
        public string Tb02021Os { get; set; }
        public decimal? Tb02021Vlrinss { get; set; }
        public decimal? Tb02021Vlrretinss { get; set; }
        public string Tb02021Contrato { get; set; }
        public DateTime? Tb02021Competencia { get; set; }
        public string Tb02021Contred { get; set; }
        public string Tb02021Coo { get; set; }
        public string Tb02021Emprestimo { get; set; }
        public decimal? Tb02021Vlrdifaliq { get; set; }
        public decimal? Tb02021Vlricmsint { get; set; }
        public decimal? Tb02021Vlricmsext { get; set; }
        public decimal? Tb02021Vlricmsfcp { get; set; }
        public int? Tb02021Lote { get; set; }
        public int? Tb02021Urgencia { get; set; }
        public decimal? Tb02021Caucao { get; set; }
        public decimal? Tb02021Vlrcaucao { get; set; }
        public string Tb02021Ndd { get; set; }
        public int? Tb02021Nddremessa { get; set; }
        public int? Tb02021Nddtiporemessa { get; set; }
        public int? Tb02021Nddpedido { get; set; }
        public string Tb02021Projeto { get; set; }
        public string Tb02021Codsite { get; set; }
        public string Tb02021Coddepto { get; set; }
        public int? Tb02021Conttotal { get; set; }
        public int? Tb02021Ordem { get; set; }
        public string Tb02021Hrdesloc { get; set; }
        public int? Tb02021Kminicial { get; set; }
        public int? Tb02021Kmfinal { get; set; }
        public decimal? Tb02021Basefcptot { get; set; }
        public decimal? Tb02021Vlrfcptot { get; set; }
        public decimal? Tb02021Basefcptotst { get; set; }
        public decimal? Tb02021Vlrfcptotst { get; set; }

        public virtual Tb01068 Tb02021ClatendeNavigation { get; set; }
        public virtual Tb01008 Tb02021CodcliNavigation { get; set; }
        public virtual Tb02177 Tb02021CoddeptoNavigation { get; set; }
        public virtual Tb02176 Tb02021CodsiteNavigation { get; set; }
        public virtual Tb02182 Tb02021ProjetoNavigation { get; set; }
    }
}